shell zsh
enabled_layouts tall,*

# --- Appearance ---
font_family      MesloLGS NF
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# Cursor
cursor_shape beam
cursor #00d7ff
active_border_color #00d7ff
shell_integration enabled

# Window layout
window_padding_width 10
remember_window_size  yes
initial_window_width  640
initial_window_height 400

# Tab bar
tab_bar_style powerline

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Background
background_opacity 0.9
dynamic_background_opacity yes

# --- Keybindings ---
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+t new_tab
map ctrl+shift+q close_tab

# Window navigation (Vim-style)
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down

# Window management
map ctrl+shift+enter launch --cwd=current --location=vsplit
map ctrl+shift+\ launch --cwd=current --location=vsplit
map ctrl+shift+s launch --cwd=current --location=hsplit
map ctrl+shift+f move_window_forward
map ctrl+shift+b move_window_backward
map ctrl+shift+l next_layout
map ctrl+shift+r start_resizing_window
map ctrl+shift+z toggle_layout stack

# Vim-like Selection Mode (Scrollback)
map ctrl+shift+k show_scrollback
copy_on_select yes

